# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import gmaps.datasets
import os

# Import API key
from config import GMap_api_key
gkey = GMap_api_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
my_city_df = pd.read_csv('../output_data/cities.csv',usecols=[1,2,3,4,5,6,7,8,9])
my_city_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Vaini,20,TO,1603166621,65,-21.20,-175.20,77.00,11.41
1,Nikolskoye,90,RU,1603166648,80,59.70,30.79,34.00,11.18
2,Albany,100,US,1603166649,79,42.60,-73.97,57.00,8.37
3,Ushuaia,75,AR,1603166488,89,-54.80,-68.30,35.60,34.45
4,Cidreira,1,BR,1603166651,93,-30.18,-50.21,66.69,12.17
...,...,...,...,...,...,...,...,...,...
557,Jadu,0,LY,1603167272,88,31.95,12.03,52.92,3.71
558,Mayskiy,0,RU,1603167273,93,47.69,40.10,39.20,4.47
559,Omboué,100,GA,1603167274,87,-1.57,9.26,76.78,7.09
560,Kawalu,91,ID,1603167275,62,-7.38,108.21,85.41,4.45
561,Te Anau,5,NZ,1603167276,52,-45.42,167.72,54.14,6.13

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Access maps with unique API key
gmaps.configure(api_key=gkey)
locations = my_city_df[['Lat','Lng']]
humidity = my_city_df['Humidity']

In [4]:
#add heatmap layer to map
heat_map = gmaps.Map()
heat_map.add_layer(gmaps.heatmap_layer(locations, weights=humidity))
heat_map

Map(configuration={'api_key': 'AIzaSyDfVCnIk2ul_JJjEKWy3m1l_osTzqfqGi4'}, data_bounds=[(-49.32362749510676, -1…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
# since I am a redhead I need some clouds but not so much that it signals rain
# I also do not like too much heat so 65-75 is my range 
# I need a little breeze 

dream_df = my_city_df.loc[my_city_df['Max Temp'] < 75, :]
dream_df = dream_df.loc[dream_df['Max Temp'] > 65, :]
dream_df = dream_df.loc[dream_df['Wind Speed'] < 15, :]
dream_df = dream_df.loc[dream_df['Wind Speed'] > 2, :]
dream_df = dream_df.loc[dream_df['Cloudiness'] < 30, :]
dream_df = dream_df.loc[dream_df['Cloudiness'] > 10, :]
dream_df.dropna()
dream_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
28,Cabedelo,20,BR,1603166678,88,-6.98,-34.83,73.40,5.82
79,Hobart,20,AU,1603166421,59,-42.88,147.33,71.01,13.87
168,Tatishchevo,12,RU,1603166835,72,51.67,45.60,68.00,6.71
193,Coruripe,14,BR,1603166733,82,-10.13,-36.18,74.25,10.67
222,Lárdos,20,GR,1603166646,72,36.09,28.02,69.01,3.36
245,Mossamedes,13,AO,1603166921,84,-15.20,12.15,66.42,3.27
268,Agüimes,20,ES,1603166947,78,27.91,-15.45,73.99,5.82
287,São José da Coroa Grande,25,BR,1603166918,78,-8.90,-35.15,74.80,9.31
294,Obo,29,CF,1603166976,96,5.40,26.49,66.92,2.48
420,Mahajanga,20,MG,1603167119,69,-15.72,46.32,73.40,5.82
460,Tūkrah,25,LY,1603167164,77,32.53,20.58,67.28,3.83

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
hotel_df = dream_df
hotel_df['Hotel']=np.nan
hotel_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel
28,Cabedelo,20,BR,1603166678,88,-6.98,-34.83,73.40,5.82,NaN
79,Hobart,20,AU,1603166421,59,-42.88,147.33,71.01,13.87,NaN
168,Tatishchevo,12,RU,1603166835,72,51.67,45.60,68.00,6.71,NaN
193,Coruripe,14,BR,1603166733,82,-10.13,-36.18,74.25,10.67,NaN
222,Lárdos,20,GR,1603166646,72,36.09,28.02,69.01,3.36,NaN
245,Mossamedes,13,AO,1603166921,84,-15.20,12.15,66.42,3.27,NaN
268,Agüimes,20,ES,1603166947,78,27.91,-15.45,73.99,5.82,NaN
287,São José da Coroa Grande,25,BR,1603166918,78,-8.90,-35.15,74.80,9.31,NaN
294,Obo,29,CF,1603166976,96,5.40,26.49,66.92,2.48,NaN
420,Mahajanga,20,MG,1603167119,69,-15.72,46.32,73.40,5.82,NaN
460,Tūkrah,25,LY,1603167164,77,32.53,20.58,67.28,3.83,NaN

In [11]:
# set up variable - names as profiled in class instruction
target_search = "Hotel"
target_radius = 5000
target_type = "lodging"

# start with counter set to zero to match index 
counter = 0

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():

    # set up a parameters dictionary
    params = {
        "location": f"{row['Lat']}, {row['Lng']}",
        "keyword": target_search,
        "radius": target_radius,
        "type": target_type,
        "key": gkey
    }
 
    # assemble url and make API request
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    # check to make sure we have a results - if yes then record in dataframe
    
    try:
        if len(results) > 0:
               hotel_name = response['results'][0]['name']
               hotel_df.iloc[counter, -1] = hotel_name
        counter = counter+1
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
hotel_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel
28,Cabedelo,20,BR,1603166678,88,-6.98,-34.83,73.40,5.82,Formosa Apart Hotel
79,Hobart,20,AU,1603166421,59,-42.88,147.33,71.01,13.87,MACq 01 Hotel
168,Tatishchevo,12,RU,1603166835,72,51.67,45.60,68.00,6.71,AURA
193,Coruripe,14,BR,1603166733,82,-10.13,-36.18,74.25,10.67,Pousada Pontal Sunset
222,Lárdos,20,GR,1603166646,72,36.09,28.02,69.01,3.36,Lindos Grand Resort & Spa
245,Mossamedes,13,AO,1603166921,84,-15.20,12.15,66.42,3.27,Hotel Chik Chik Namibe
268,Agüimes,20,ES,1603166947,78,27.91,-15.45,73.99,5.82,Villa Nestor
287,São José da Coroa Grande,25,BR,1603166918,78,-8.90,-35.15,74.80,9.31,Pousada Barra Velha
294,Obo,29,CF,1603166976,96,5.40,26.49,66.92,2.48,NaN
420,Mahajanga,20,MG,1603167119,69,-15.72,46.32,73.40,5.82,Lodge des Terres Blanches
460,Tūkrah,25,LY,1603167164,77,32.53,20.58,67.28,3.83,قاعدة فيقا فيقا

In [13]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [14]:
# Add marker layer ontop of heat map
# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations)

# Add the layer to the map
heat_map.add_layer(markers)
heat_map

# Display figure
heat_map

Map(configuration={'api_key': 'AIzaSyDfVCnIk2ul_JJjEKWy3m1l_osTzqfqGi4'}, data_bounds=[(-49.458949977312024, -…